# Copyright 2026 TechnoLibre - Mathieu Benoit
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "ERPLibre Construction QC (sync demo)",
    "category": "Tools",
    "summary": "Quebec-construction example of the external-sync chain",
    "version": "18.0.1.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "website": "https://erplibre.ca",
    "application": True,
    "installable": True,
    "depends": [
        "erplibre_sync_external_data_spreadsheet",
        "project",
        "mail",
        "helpdesk_mgmt",
        "sale",
        "crm",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/sync_model.xml",
        # Views + menus generated by erplibre_devops (code.generator), see
        # README "Regenerate the views". Per-model view files first, then menu.
        "views/construction_doc_soumission.xml",
        "views/construction_doc_facture.xml",
        "views/construction_doc_devis.xml",
        "views/construction_doc_intervenant.xml",
        "views/menu.xml",
    ],
}
