# Copyright 2026 TechnoLibre - Mathieu Benoit
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
import json
import os
import re

from odoo.addons.erplibre_event_table.models.event_table import (
    CONNECTOR_WIDTH,
    LIST_COMPANY_LINE_HEIGHT,
    LIST_FULL_NAME_LINE_HEIGHT,
    LIST_FULL_NAME_ONE_LINE_CHARS,
    LIST_LINE_HEIGHT,
    LIST_WIDTH,
    LIST_WIDTH_FULL,
    PARTY_BASE_SPAN,
    PARTY_SPAN_PER_SEAT,
    list_line_pitch,
    list_reserved_height,
    list_width,
    list_wraps_to_two_lines,
    visual_table_size,
)
from odoo.tests.common import BaseCase

# static/tests/visual_table_size_fixture.js: frozen output from the
# real, shipped visualTableSize (geometry.js), generated by
# generate_visual_table_size_fixture.mjs alongside it. Read as plain
# text here, never through a JS parser or by importing the generator
# cross-language, since either would only move the twin this file
# exists to pin one level further away.
_FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "static",
    "tests",
    "visual_table_size_fixture.js",
)
_SIZE_MARKER = "export const VISUAL_TABLE_SIZE_FIXTURE = "
_RESERVATION_MARKER = "export const LIST_RESERVATION_FIXTURE = "
_RESERVED_HEIGHT_MARKER = "export const LIST_RESERVED_HEIGHT_FIXTURE = "
# An array's own closing bracket, alone on its line at column 0, which
# is where both the generator and ./script/maintenance/format.sh put
# the end of a top-level `export const <NAME> = [...]`. Reading to it,
# rather than to the end of the file, is what lets the file carry more
# than one fixture.
_ARRAY_END_PATTERN = re.compile(r"^\];$", re.M)
# The generator writes the array as plain JSON, but
# ./script/maintenance/format.sh reformats the file into idiomatic JS
# on every run (bare keys, a trailing comma before `}`/`]`) — both
# forms have to keep parsing here, or this test would start failing
# the next time someone runs the formatter, for a reason that has
# nothing to do with the two functions it exists to compare. Narrow on
# purpose: only the six field names this fixture ever uses are quoted,
# and only a comma immediately before a closing brace or bracket is
# dropped — not a general JS-to-JSON parser, since a flat array of
# flat objects with six known fields and no string value containing a
# colon, a comma or a brace is the only input this ever has to handle.
_BARE_KEY_PATTERN = re.compile(
    r"\b(shape|seatCount|assignSeats|showCompany|showFullNames"
    r"|labelLength|wrapsToTwoLines|chipCount|wrappingChipCount"
    r"|width|height|linePitch)\b\s*:"
)
_TRAILING_COMMA_PATTERN = re.compile(r",(\s*[}\]])")

# static/src/floor_plan/geometry.js, read as plain text for the same
# reason the fixture above is: importing it cross-language would only
# move the twin one level further away. The name-list constants live in
# both files, and nothing but this check stops one copy from being
# edited alone.
_GEOMETRY_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "static",
    "src",
    "floor_plan",
    "geometry.js",
)


def _js_constant(name):
    """Reads `export const <name> = <number>;` out of geometry.js.

    Raises rather than returning a default when the declaration is
    absent: a missing constant means the two files no longer describe
    the same thing, which is precisely what this has to report.
    """
    with open(_GEOMETRY_PATH, encoding="utf-8") as geometry_file:
        text = geometry_file.read()
    match = re.search(
        rf"^export const {name} = (-?[0-9]+(?:\.[0-9]+)?);$", text, re.M
    )
    if not match:
        raise AssertionError(
            f"geometry.js declares no `export const {name} = <number>;` —"
            " the two halves of this constant no longer match."
        )
    return float(match.group(1))


def _js_object_literal_to_json(body):
    body = _BARE_KEY_PATTERN.sub(r'"\1":', body)
    return _TRAILING_COMMA_PATTERN.sub(r"\1", body)


def _load_fixture(marker):
    """Extracts one of the arrays visual_table_size_fixture.js exports,
    by finding its own marker and its own closing bracket rather than
    parsing JavaScript — the file's own header states this is exactly
    what keeps the extraction working, and why hand-editing a row
    instead of regenerating the file would break it, loudly, rather
    than silently reading a stale or malformed row.
    """
    with open(_FIXTURE_PATH, encoding="utf-8") as fixture_file:
        text = fixture_file.read()
    if marker not in text:
        raise AssertionError(
            f"visual_table_size_fixture.js exports no `{marker.strip()}`"
            " — regenerate it with"
            " generate_visual_table_size_fixture.mjs rather than"
            " hand-editing it."
        )
    start = text.index(marker) + len(marker)
    end = _ARRAY_END_PATTERN.search(text, start)
    if not end:
        raise AssertionError(
            "visual_table_size_fixture.js no longer closes its array"
            " with a `];` of its own line — regenerate it with"
            " generate_visual_table_size_fixture.mjs rather than"
            " hand-editing a row."
        )
    return json.loads(
        _js_object_literal_to_json(text[start : end.start() + 1])
    )


class TestVisualTableSizeMatchesJs(BaseCase):
    """Pins visual_table_size (event_table.py) against the SAME frozen
    rows geometry.test.js checks visualTableSize (JS) against, so the
    two functions drifting apart — the exact way step_y and floorSize,
    then the rim term and seatPositions, drifted before — fails a test
    on this side, not only a comment or a report that says they agreed
    once. Needs no database: visual_table_size is a pure function.
    """

    def test_every_fixture_row_matches_the_python_twin(self):
        rows = _load_fixture(_SIZE_MARKER)
        self.assertTrue(rows, "the fixture is empty — nothing was pinned")
        for row in rows:
            width, height = visual_table_size(
                row["shape"],
                row["seatCount"],
                row["assignSeats"],
                row["showCompany"],
            )
            self.assertAlmostEqual(
                width, row["width"], places=6, msg=f"width mismatch for {row}"
            )
            self.assertAlmostEqual(
                height,
                row["height"],
                places=6,
                msg=f"height mismatch for {row}",
            )

    def test_the_shared_constants_match_their_javascript_twins(self):
        """Pins the shared constants against geometry.js's own text.
        Seven size the name list — the column, the wider column whole
        names ask for, the pitch of a chip carrying the name alone,
        what the company line adds to that pitch, what a wrapped name's
        second line adds to it, how many characters that wider line
        holds before a name needs the second one, and the connector
        reaching the list — and BOTH languages compute a floor and a
        grid from them: _grid_positions here, floorSize there. The other two are the party floor, the one term
        of visual_table_size that grows with the seat count, computed in
        both languages as well. Nothing else would notice one copy being
        edited alone, which is how every other twin in this module
        drifted before it was pinned.
        """
        for name, python_value in (
            ("LIST_WIDTH", LIST_WIDTH),
            ("LIST_WIDTH_FULL", LIST_WIDTH_FULL),
            ("LIST_LINE_HEIGHT", LIST_LINE_HEIGHT),
            ("LIST_COMPANY_LINE_HEIGHT", LIST_COMPANY_LINE_HEIGHT),
            ("LIST_FULL_NAME_LINE_HEIGHT", LIST_FULL_NAME_LINE_HEIGHT),
            (
                "LIST_FULL_NAME_ONE_LINE_CHARS",
                LIST_FULL_NAME_ONE_LINE_CHARS,
            ),
            ("CONNECTOR_WIDTH", CONNECTOR_WIDTH),
            ("PARTY_BASE_SPAN", PARTY_BASE_SPAN),
            ("PARTY_SPAN_PER_SEAT", PARTY_SPAN_PER_SEAT),
        ):
            self.assertEqual(
                _js_constant(name),
                python_value,
                msg=(
                    f"{name} is {python_value} in event_table.py but"
                    f" {_js_constant(name)} in geometry.js"
                ),
            )

    def test_the_fixture_still_covers_the_whole_sweep(self):
        """Pins the fixture's own REACH, not only its values. The
        row-by-row check above passes just as well on a fixture narrowed
        to a single seat count: every remaining row still matches, while
        the crossovers, the corner solver's active range and the
        large-seat-count tail go unchecked without one test going red.
        geometry.test.js pins the same two figures on the JS side, so
        narrowing the generator fails on both.
        """
        rows = _load_fixture(_SIZE_MARKER)
        self.assertEqual(len(rows), 92)
        self.assertEqual(
            sorted({row["seatCount"] for row in rows}),
            [
                2,
                4,
                8,
                10,
                11,
                12,
                14,
                15,
                16,
                17,
                20,
                25,
                30,
                45,
                50,
                51,
                52,
                60,
                100,
                200,
                500,
                1000,
            ],
        )

    def test_every_reservation_row_matches_the_python_twin(self):
        """Pins list_width, list_wraps_to_two_lines and list_line_pitch
        against the SAME frozen rows geometry.test.js checks their
        JavaScript halves against. The constants check above would pass
        on a Python twin that MULTIPLIED where the JavaScript one adds,
        that let one option replace the other instead of composing, or
        that compared a label with >= where the other uses >: the
        numbers would still match, the formulas would not.
        """
        rows = _load_fixture(_RESERVATION_MARKER)
        self.assertEqual(len(rows), 20)
        # Both booleans swept whole, and the label swept ACROSS the
        # threshold: a sweep stopping short of the two lengths that
        # straddle it would pin everything except the one figure a
        # threshold can get wrong.
        self.assertEqual(
            {(row["showCompany"], row["showFullNames"]) for row in rows},
            {(False, False), (False, True), (True, False), (True, True)},
        )
        self.assertTrue(
            {
                LIST_FULL_NAME_ONE_LINE_CHARS,
                LIST_FULL_NAME_ONE_LINE_CHARS + 1,
            }.issubset({row["labelLength"] for row in rows}),
            "the sweep no longer straddles the threshold",
        )
        for row in rows:
            self.assertEqual(
                list_width(row["showFullNames"]),
                row["width"],
                msg=f"list width mismatch for {row}",
            )
            self.assertEqual(
                list_wraps_to_two_lines(
                    row["showFullNames"], row["labelLength"]
                ),
                row["wrapsToTwoLines"],
                msg=f"wrap decision mismatch for {row}",
            )
            self.assertEqual(
                list_line_pitch(row["showCompany"], row["wrapsToTwoLines"]),
                row["linePitch"],
                msg=f"line pitch mismatch for {row}",
            )

    def test_every_reserved_height_row_matches_the_python_twin(self):
        """Pins list_reserved_height against the SAME frozen rows
        geometry.test.js checks listReservedHeight against. This is the
        formula a list's whole height comes from, and the rows that
        matter are the MIXED ones — a table where some chips wrap and
        others do not. A twin that multiplied one pitch by a whole list
        matches every unmixed row exactly and gets those wrong by a
        line per chip, which is the reservation this file exists to
        keep honest.
        """
        rows = _load_fixture(_RESERVED_HEIGHT_MARKER)
        self.assertEqual(len(rows), 18)
        mixed = [
            row
            for row in rows
            if 0 < row["wrappingChipCount"] < row["chipCount"]
        ]
        self.assertTrue(mixed, "the sweep pins no mixed list at all")
        for row in rows:
            self.assertEqual(
                list_reserved_height(
                    row["chipCount"],
                    row["wrappingChipCount"],
                    row["showCompany"],
                ),
                row["height"],
                msg=f"reserved height mismatch for {row}",
            )
        # The property the fixture cannot state on its own: a mixed
        # list stands strictly between the two uniform ones, so a twin
        # that collapsed to either end fails here as well as row by
        # row.
        for row in mixed:
            chips, show_company = row["chipCount"], row["showCompany"]
            self.assertLess(
                list_reserved_height(chips, 0, show_company),
                row["height"],
            )
            self.assertLess(
                row["height"],
                list_reserved_height(chips, chips, show_company),
            )

    def test_no_row_draws_a_smaller_table_than_the_row_one_seat_below(self):
        """The two checks above pin AGREEMENT — this side against frozen
        rows, and geometry.test.js against the same ones — never
        JUSTNESS: a size that shrinks when a seat is added matches just
        as exactly on both sides, and was certified conforming by both
        for as long as it stood. This is the missing property, read off
        the SAME rows: group them by everything that is not the seat
        count, sort each group by seat count, and check that neither
        side of the table ever gets shorter from one row to the next.
        Collected into a list and compared to an empty one rather than
        asserted pair by pair, so a failure names every offending pair
        at once instead of stopping at the first. The JavaScript twin
        runs the same grouping over the same file.
        """
        series = {}
        for row in _load_fixture(_SIZE_MARKER):
            key = (row["shape"], row["assignSeats"], row["showCompany"])
            series.setdefault(key, []).append(row)
        shrinks = []
        for key, rows in series.items():
            rows = sorted(rows, key=lambda row: row["seatCount"])
            for smaller, bigger in zip(rows, rows[1:]):
                if (
                    bigger["width"] < smaller["width"] - 1e-9
                    or bigger["height"] < smaller["height"] - 1e-9
                ):
                    shrinks.append(
                        f"{key}: {smaller['seatCount']} seats draw"
                        f" {smaller['width']:.2f}x{smaller['height']:.2f},"
                        f" {bigger['seatCount']} draw"
                        f" {bigger['width']:.2f}x{bigger['height']:.2f}"
                    )
        self.assertEqual(shrinks, [])
