{
    "name": "Tdm",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "website": "https://technolibre.ca",
    "application": True,
    "depends": ["portal", "membership", "survey"],
    "data": [
        "security/ir.model.access.csv",
        "data/tdm_travailleur_stage.xml",
        "data/tdm_secteur_activite.xml",
        "data/tdm_offre_emploi_type.xml",
        "data/tdm_entrevue_stage.xml",
        "data/tdm_offre_emploi_applique_stage.xml",
        "data/tdm_offre_emploi_stage.xml",
        "views/res_partner.xml",
        "views/product_views.xml",
        "views/tdm_entrevue.xml",
        "views/tdm_templates.xml",
        "views/tdm_entrevue_stage.xml",
        "views/tdm_offre_emploi.xml",
        "views/tdm_offre_emploi_applique.xml",
        "views/tdm_offre_emploi_applique_stage.xml",
        "views/tdm_offre_emploi_stage.xml",
        "views/tdm_travailleur_stage.xml",
        "views/tdm_offre_emploi_category.xml",
        "views/tdm_offre_emploi_tag.xml",
        "views/tdm_offre_emploi_type.xml",
        "views/tdm_secteur_activite.xml",
        "views/menu.xml",
    ],
    "installable": True,
}
