{
    "name": "Tdm",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "website": "https://technolibre.ca",
    "application": True,
    "depends": ["portal"],
    "data": [
        "security/ir.model.access.csv",
        "views/tdm_entrevue.xml",
        "views/tdm_templates.xml",
        "views/tdm_entrevue_stage.xml",
        "views/tdm_offre_emploi.xml",
        "views/tdm_offre_emploi_applique.xml",
        "views/tdm_offre_emploi_applique_stage.xml",
        "views/tdm_offre_emploi_stage.xml",
        "views/tdm_profil_entreprise.xml",
        "views/tdm_profil_entreprise_stage.xml",
        "views/tdm_profil_travailleur.xml",
        "views/tdm_profil_travailleur_stage.xml",
        "views/menu.xml",
    ],
    "installable": True,
}
